serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${role_arn}"

settings:
  clusterName: "${cluster_name}"
  clusterEndpoint: "${cluster_endpoint}"
  aws:
    defaultInstanceProfile: "${instance_profile}"
