serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "${role_arn}"

nodeSelector:
  karpenter.sh/controller: 'true'

settings:
  clusterName: "${cluster_name}"
  clusterEndpoint: "${cluster_endpoint}"
  aws:
    defaultInstanceProfile: "${instance_profile}"
