name: pre-commit checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:   # <-- This enables manual runs from the Actions tab

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pre-commit and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install OpenTofu
        run: |
          curl -sLo tofu.tar.gz https://github.com/opentofu/opentofu/releases/latest/download/opentofu_linux_amd64.tar.gz
          tar -xzf tofu.tar.gz
          sudo mv tofu /usr/local/bin/
          tofu --version

      - name: Run pre-commit checks on all files
        run: pre-commit run --all-files
