name: pre-commit checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:   # <-- This enables manual runs from the Actions tab

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install asdf version manager
        run: |
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.18.0
          echo '. "$HOME/.asdf/asdf.sh"' >> $GITHUB_ENV
          echo '. "$HOME/.asdf/completions/asdf.bash"' >> $GITHUB_ENV

      - name: Install tool dependencies with asdf
        run: |
          . "$HOME/.asdf/asdf.sh"
          asdf plugin update --all || true
          asdf install

      - name: Cache pre-commit and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

#      - name: Install pre-commit
#        run: pip install pre-commit

#      - name: Install OpenTofu
#        run: |
#          TOFU_VERSION=1.10.2
#          curl -sLo tofu.tar.gz https://github.com/opentofu/opentofu/releases/download/v${TOFU_VERSION}/tofu_${TOFU_VERSION}_linux_amd64.tar.gz
#          tar -xzf tofu.tar.gz
#          sudo mv tofu /usr/local/bin/
#          tofu --version

#      - name: Run pre-commit checks on all files
#        run: pre-commit run --all-files
